spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moovsmart?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: zoli2002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  security:
    user:
      name: zoli
  mail:
    host: smtp.gmail.com
    port: 587
    username: moovsmartproject@gmail.com
    properties.mail.smtp.starttls.enable: true
    password: Moov2002
    url: http://localhost:4200/#/

logging:
  level:
    com.progmasters: debug
    org.springframework.web: info
    org.hibernate: error
    org:
      springframework:
        security: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: src/main/resources/logger/moovsmart_logger.log
